/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.DAOS.EmprestimosDAO;
import modelo.DAOS.LivrosDAO;
import modelo.DAOS.UsuariosDAO;
import modelo.Emprestimo;
import modelo.Livro;
import modelo.Usuario;
import negocio.Negocios;

/**
 *
 * @author Leonardo
 */
public class FormEmprestimos extends javax.swing.JDialog {

    EmprestimosDAO daoEmprestimos = new EmprestimosDAO();
    Emprestimo emprestimo = new Emprestimo();
    LivrosDAO daoLivros = new LivrosDAO();
    Negocios negocio = new Negocios();
    UsuariosDAO daoUser = new UsuariosDAO();

    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Date data = new Date();

    /*Atualiza a tabela na primeira vez que se abre o form*/
    /*Retorna todos os elementos*/
    public void atualizaTabela() throws SQLException {
        listResultadoConsultas.clear();
        listResultadoConsultas.addAll(daoEmprestimos.buscarTodos());
        int linha = listResultadoConsultas.size() - 1; // retorna o numero de linhas
        if (linha >= 0) {
            tblResultadoConsultas.setRowSelectionInterval(linha, linha);
            tblResultadoConsultas.scrollRectToVisible(
                    tblResultadoConsultas.getCellRect(linha, linha, true));
        }
    }

    /*Atualiza a tabela a partir de um parametro de busca*/
    /*Retorna apenas os elementos solicitados com a busca*/
    public void atualizaTabela2() throws SQLException {
        listResultadoConsultas.clear();
        listResultadoConsultas.addAll(daoEmprestimos.buscar());
        int linha = listResultadoConsultas.size() - 1; // retorna o numero de linhas
        if (linha >= 0) {
            tblResultadoConsultas.setRowSelectionInterval(linha, linha);
            tblResultadoConsultas.scrollRectToVisible(
                    tblResultadoConsultas.getCellRect(linha, linha, true));
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum emprestimo encontrado");
        }
    }

    /**
     * Creates new form FormConsultaLivros
     */
    public FormEmprestimos(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listResultadoConsultas = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Emprestimo>())  ;
        painelConsultas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConsultaTitulo = new javax.swing.JTextField();
        txtConsultaLogin = new javax.swing.JTextField();
        btnOkTitulo = new javax.swing.JButton();
        btnOkISBN = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtConsultaPorUsuario = new javax.swing.JTextField();
        btnOkUsuario = new javax.swing.JButton();
        btnDevolverLivro = new javax.swing.JButton();
        btnRenovar = new javax.swing.JButton();
        painelResultadoConsultas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultadoConsultas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("Consulta por Titulo:");

        jLabel2.setText("Consulta por ISBN:");

        txtConsultaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaTituloActionPerformed(evt);
            }
        });

        txtConsultaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaLoginActionPerformed(evt);
            }
        });

        btnOkTitulo.setText("Ok");
        btnOkTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkTituloActionPerformed(evt);
            }
        });

        btnOkISBN.setText("Ok");
        btnOkISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkISBNActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel3.setText("Consulta por Usuario");

        txtConsultaPorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaPorUsuarioActionPerformed(evt);
            }
        });

        btnOkUsuario.setText("Ok");

        btnDevolverLivro.setText("Devolver Livro");
        btnDevolverLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverLivroActionPerformed(evt);
            }
        });

        btnRenovar.setText("Renovar ");
        btnRenovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenovarActionPerformed(evt);
            }
        });

        painelResultadoConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados das consultas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listResultadoConsultas, tblResultadoConsultas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${user.nome}"));
        columnBinding.setColumnName("Usuário");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dt_retirada}"));
        columnBinding.setColumnName("Retirada");
        columnBinding.setColumnClass(java.sql.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dt_entrega}"));
        columnBinding.setColumnName("Entrega");
        columnBinding.setColumnClass(java.sql.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${user.login}"));
        columnBinding.setColumnName("Login");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblResultadoConsultas);

        javax.swing.GroupLayout painelResultadoConsultasLayout = new javax.swing.GroupLayout(painelResultadoConsultas);
        painelResultadoConsultas.setLayout(painelResultadoConsultasLayout);
        painelResultadoConsultasLayout.setHorizontalGroup(
            painelResultadoConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResultadoConsultasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelResultadoConsultasLayout.setVerticalGroup(
            painelResultadoConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResultadoConsultasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelConsultasLayout = new javax.swing.GroupLayout(painelConsultas);
        painelConsultas.setLayout(painelConsultasLayout);
        painelConsultasLayout.setHorizontalGroup(
            painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsultasLayout.createSequentialGroup()
                        .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelConsultasLayout.createSequentialGroup()
                                .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelConsultasLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtConsultaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultasLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtConsultaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(painelConsultasLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addComponent(txtConsultaPorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOkTitulo)
                            .addComponent(btnOkISBN)
                            .addComponent(btnOkUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnDevolverLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnRenovar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(painelResultadoConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelConsultasLayout.setVerticalGroup(
            painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsultaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkTitulo)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnOkISBN)
                    .addComponent(txtConsultaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolverLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConsultaPorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkUsuario)
                    .addComponent(btnRenovar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelResultadoConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultaTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaTituloActionPerformed

    private void txtConsultaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaLoginActionPerformed

    /*Função que busca os emprestimos que possuim determinado titulo do livro*/
    private void btnOkTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkTituloActionPerformed
        /*String busca é um concatenação de sql busca com o parametro passado como busca*/
        String busca = daoEmprestimos.getSqlBusca() + "\nWHERE l.titulo ILIKE " + "'%" + txtConsultaTitulo.getText() + "%'" ;
        
        daoEmprestimos.setSqlBusca(busca);

        try {
            atualizaTabela2();
            txtConsultaTitulo.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(FormEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOkTituloActionPerformed

    
    
    /*Função que busca os emprestimos que possuem determinado isbn do livro*/
    private void btnOkISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkISBNActionPerformed
        daoEmprestimos.setSqlBusca("SELECT * FROM usuarios WHERE login ILIKE " + "'%" + txtConsultaLogin.getText() + "%'");
        try {
            atualizaTabela();
            txtConsultaTitulo.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(FormEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOkISBNActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtConsultaPorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaPorUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaPorUsuarioActionPerformed

    /*Função usada para a devolução do livro*/
    /*Faz todas as verificações com relação a data de entrega do livro*/
    /*Verifica se será aplicada alguma multa ao cliente*/
    private void btnDevolverLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverLivroActionPerformed
        int linhaSelecionada = tblResultadoConsultas.getSelectedRow();
        emprestimo = listResultadoConsultas.get(linhaSelecionada);
        Livro l = emprestimo.getLivro();
        Usuario u = emprestimo.getUser();
        
        System.out.println("Dentro do devolver livro : " + u.getLogin());
        System.out.println("Nome do usuario dentro do devolver : :" + u.getNome());
        System.out.println("Outra tentativa : " + emprestimo.getUser().getLogin());
        
        java.util.Date dataRecebimento = new java.util.Date(); //data em que o livro é devolvido
        java.sql.Date dtRecebimento = new java.sql.Date(dataRecebimento.getTime()); //conversão de datas
        int multa = negocio.controlaMulta(emprestimo, (java.sql.Date) dtRecebimento);

        if (multa == 0) {
            l.setEmprestado(false);
            u.setN_exemplares(u.getN_exemplares() - 1);
        } else {
            u.setMulta(u.getMulta() + multa);
            l.setEmprestado(false);
            u.setN_exemplares(u.getN_exemplares() - 1);
        }

        daoLivros.alterar(l);
        daoUser.alterar(u);
        daoEmprestimos.excluir(emprestimo);
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            Logger.getLogger(FormEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDevolverLivroActionPerformed

    /*Função usada para a renovação dos emprestimos*/
    private void btnRenovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovarActionPerformed
        int linhaSelecionada = tblResultadoConsultas.getSelectedRow();
        emprestimo = listResultadoConsultas.get(linhaSelecionada);
        Livro l = emprestimo.getLivro();
        Usuario u = emprestimo.getUser();
        java.util.Date dataRecebimento = new java.util.Date();
        java.sql.Date dtRecebimento = new java.sql.Date(dataRecebimento.getTime());

        if (negocio.verificaAtraso(emprestimo, dtRecebimento) && negocio.verificaReserva(emprestimo.getLivro())) {
            Date dt_entrega = negocio.dataEntrega(u);
            emprestimo.setDt_entrega((java.sql.Date) dt_entrega);
            daoEmprestimos.alterar(emprestimo);
        } else {
            JOptionPane.showMessageDialog(this, "Renovação não efetuada");
        }

        try {
            atualizaTabela();
        } catch (SQLException ex) {
            Logger.getLogger(FormEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRenovarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormEmprestimos dialog = null;
                try {
                    dialog = new FormEmprestimos(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnDevolverLivro;
    protected javax.swing.JButton btnFechar;
    protected javax.swing.JButton btnOkISBN;
    protected javax.swing.JButton btnOkTitulo;
    protected javax.swing.JButton btnOkUsuario;
    protected javax.swing.JButton btnRenovar;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JScrollPane jScrollPane1;
    protected java.util.List<Emprestimo> listResultadoConsultas;
    protected javax.swing.JPanel painelConsultas;
    protected javax.swing.JPanel painelResultadoConsultas;
    protected javax.swing.JTable tblResultadoConsultas;
    protected javax.swing.JTextField txtConsultaLogin;
    protected javax.swing.JTextField txtConsultaPorUsuario;
    protected javax.swing.JTextField txtConsultaTitulo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
