/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.DAOS.EmprestimosDAO;
import modelo.DAOS.LivrosDAO;
import modelo.DAOS.ReservasDAO;
import modelo.DAOS.UsuariosDAO;
import modelo.Emprestimo;
import modelo.Livro;
import modelo.Reserva;
import modelo.Usuario;
import negocio.Negocios;

/**
 *
 * @author Leonardo
 */
public class FormReservas extends javax.swing.JDialog {

    ReservasDAO daoReservas = new ReservasDAO();
    Reserva res = new Reserva();
    LivrosDAO daoLivros = new LivrosDAO();
    Negocios negocio = new Negocios();
    UsuariosDAO daoUser = new UsuariosDAO();

    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Date data = new Date();

    public void atualizaTabela() throws SQLException {
        listResultadoConsultas.clear();
        listResultadoConsultas.addAll(daoReservas.buscarTodos());
        int linha = listResultadoConsultas.size() - 1; // retorna o numero de linhas
        if (linha >= 0) {
            tblResultadoConsultas.setRowSelectionInterval(linha, linha);
            tblResultadoConsultas.scrollRectToVisible(
                    tblResultadoConsultas.getCellRect(linha, linha, true));
        }
    }

    /*public void atualizaTabela2() throws SQLException {
        listResultadoConsultas.clear();
        listResultadoConsultas.addAll(daoEmprestimos.buscar());
        int linha = listResultadoConsultas.size() - 1; // retorna o numero de linhas
        if (linha >= 0) {
            tblResultadoConsultas.setRowSelectionInterval(linha, linha);
            tblResultadoConsultas.scrollRectToVisible(
                    tblResultadoConsultas.getCellRect(linha, linha, true));
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum emprestimo encontrado");
        }
    }*/

    /**
     * Creates new form FormConsultaLivros
     */
    public FormReservas(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listResultadoConsultas = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Reserva>())  ;
        painelConsultas = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtConsultaPorUsuario = new javax.swing.JTextField();
        btnOkUsuario = new javax.swing.JButton();
        btnCancelaReserva = new javax.swing.JButton();
        painelResultadoConsultas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultadoConsultas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel3.setText("Consulta por Usuario");

        txtConsultaPorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaPorUsuarioActionPerformed(evt);
            }
        });

        btnOkUsuario.setText("Ok");

        btnCancelaReserva.setText("Cancelar Reserva");
        btnCancelaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaReservaActionPerformed(evt);
            }
        });

        painelResultadoConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados das consultas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listResultadoConsultas, tblResultadoConsultas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${livro.titulo}"));
        columnBinding.setColumnName("Titulo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${user.nome}"));
        columnBinding.setColumnName("Usuario");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dt_reserva}"));
        columnBinding.setColumnName("Data de Reserva");
        columnBinding.setColumnClass(java.sql.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblResultadoConsultas);

        javax.swing.GroupLayout painelResultadoConsultasLayout = new javax.swing.GroupLayout(painelResultadoConsultas);
        painelResultadoConsultas.setLayout(painelResultadoConsultasLayout);
        painelResultadoConsultasLayout.setHorizontalGroup(
            painelResultadoConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        painelResultadoConsultasLayout.setVerticalGroup(
            painelResultadoConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelConsultasLayout = new javax.swing.GroupLayout(painelConsultas);
        painelConsultas.setLayout(painelConsultasLayout);
        painelConsultasLayout.setHorizontalGroup(
            painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelResultadoConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtConsultaPorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOkUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelConsultasLayout.setVerticalGroup(
            painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConsultaPorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkUsuario)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelResultadoConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtConsultaPorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaPorUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaPorUsuarioActionPerformed

    private void btnCancelaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaReservaActionPerformed
        /*int linhaSelecionada = tblResultadoConsultas.getSelectedRow();
        //emprestimo = listResultadoConsultas.get(linhaSelecionada);
        Livro l = emprestimo.getLivro();
        Usuario u = emprestimo.getUser();
        java.util.Date dataRecebimento = new java.util.Date();
        java.sql.Date dtRecebimento = new java.sql.Date(dataRecebimento.getTime());

        if (negocio.verificaAtraso(emprestimo, dtRecebimento) && negocio.verificaReserva(emprestimo.getLivro())) {
            Date dt_entrega = negocio.dataEntrega(u);
            emprestimo.setDt_entrega((java.sql.Date) dt_entrega);
            daoEmprestimos.alterar(emprestimo);
        } else {
            JOptionPane.showMessageDialog(this, "Renovação não efetuada");
        }

        try {
            atualizaTabela();
        } catch (SQLException ex) {
            Logger.getLogger(FormReservas.class.getName()).log(Level.SEVERE, null, ex);
        }*/

    }//GEN-LAST:event_btnCancelaReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormReservas dialog = null;
                try {
                    dialog = new FormReservas(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormReservas.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnCancelaReserva;
    protected javax.swing.JButton btnFechar;
    protected javax.swing.JButton btnOkUsuario;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JScrollPane jScrollPane1;
    protected java.util.List<Reserva> listResultadoConsultas;
    protected javax.swing.JPanel painelConsultas;
    protected javax.swing.JPanel painelResultadoConsultas;
    protected javax.swing.JTable tblResultadoConsultas;
    protected javax.swing.JTextField txtConsultaPorUsuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
